### ISSUE TITLE
Sending an invalid value crashes the server

### ISSUE THREAD

**Issue by cheapie** [VanessaE/nixie_tubes#1]
I accidentally sent "blank" instead of "off", and it crashed the server here (line 45):
	local num = tonumber(msg)
	if msg == "colon" or msg == "period" or msg == "off" or (num >= 0 and num <= 9) then

First, it tries to convert "blank" to a number, which results in nil. This is fine, but then once the checking if it's "colon", "period", or "off" all falls through, it tries to check "nil >= 0". Comparing a number with nil is invalid, and this crashes the server.

This seems to work, but I haven't tested it all that thoroughly:
	local num = tonumber(msg)
	if msg == "colon" or msg == "period" or msg == "off" or (num and (num >= 0 and num <= 9)) then

**Comment by VanessaE** [comment]
c3199a3d2b95b501aee757b15d8ce0c819f4bf74
